### ISSUE TITLE
QR Generate in web domian

### ISSUE THREAD

**Issue by kzeke** [meravi/QR-Scanner-Generator#1]
It is working through localhost, but when I upload it to my domain, I get series of errors.
I'm stack with this error, i need your help

Fatal error: Uncaught Error: Call to undefined function ImageCreate() in /app/qr-generator/meRaviQr/qrimage.php:74 Stack trace: #0 /app/qr-generator/meRaviQr/qrimage.php(32): QRimage::image(Array, '5', '5', 16777215, 0) #1 /app/qr-generator/meRaviQr/qrencode.php(513): QRimage::png(Array, 'userQr/meravi36...', '5', '5', false, 16777215, 0) #2 /app/qr-generator/meRaviQr/qrencode.php(286): QRencode->encodePNG('f13ba28db45b860...', 'userQr/meravi36...', false) #3 /app/qr-generator/index.php(25): QRcode::png('f13ba28db45b860...', 'userQr/meravi36...', 'Q', '5', '5') #4 {main} thrown in /app/qr-generator/meRaviQr/qrimage.php on line 74

**Comment by renatocristian** [comment]
habilitar a extension=gd em php in
